volumes:
  database_data:
    driver: local

services:
  db:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432
    volumes:
      - database_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  phoenix:
    image: arizephoenix/phoenix:version-10.9.1-nonroot
    depends_on:
      - db
    ports:
      - "6006:6006" # UI and OTLP HTTP collector
      - "4317:4317" # OTLP gRPC collector
    environment:
      - PHOENIX_SQL_DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - phoenix
    ports:
      # For Hayhooks
      - "1416:1416"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - HAYSTACK_TELEMETRY_ENABLED=False
      # For observability
      - COLLECTOR_ENDPOINT=http://phoenix:6006
      ## Configure Hayhooks
      # Useful for development
      - HAYHOOKS_SHOW_TRACEBACKS=true
      # TODO: add CORS settings
      # https://docs.haystack.deepset.ai/docs/hayhooks#environment-variables
    healthcheck:
      test: [ "CMD", "wget", "--tries=1", "http://localhost:1416/status" ]
      interval: 60s
      timeout: 1s
      retries: 5

  frontend:
    # profiles: [ "disabled" ]
    build: frontend
    ports:
      - "8501:8501"
    depends_on:
      backend:
        condition: service_healthy
