[project]
name = "frontend"
version = "0.1.0"
description = "Streamlit frontend"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "presidio-analyzer>=2.2.359",
    "presidio-anonymizer>=2.2.359",
    "requests>=2.32.4",
    "spacy>=3.8.7",
    "streamlit>=1.45.1",
]
